import { useCallback, useEffect, useState } from 'react'
import { FileSignature, Plus } from 'lucide-react'
import { getCurrentUser, supabase } from '../lib/supabase'

const statusLabels = { rascunho: 'Rascunho', pendente: 'Pendente', assinado: 'Assinado', expirado: 'Expirado', cancelado: 'Cancelado' }

export default function AssinaturaDigital() {
  const [documents, setDocuments] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({ nome: '', tipo: 'contrato' })
  const load = useCallback(async () => { const { data } = await supabase.from('documentos_assinatura').select('*, clientes(nome), casos(titulo)').order('created_at', { ascending: false }); setDocuments(data || []) }, [])
  useEffect(() => { load() }, [load])
  async function createDocument(event) { event.preventDefault(); const user = await getCurrentUser(); if (!user) return alert('Sua sessão expirou. Entre novamente.'); const { data, error } = await supabase.from('documentos_assinatura').insert({ ...form, user_id: user.id }).select().single(); if (error) return alert(error.message); setDocuments((current) => [data, ...current]); setForm({ nome: '', tipo: 'contrato' }); setShowForm(false) }
  return <div className="fade-in" style={{ padding: 24, maxWidth: 1100 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}><div><h1 style={{ fontSize: 24 }}>Assinatura Digital</h1><p style={{ color: 'var(--text3)', fontSize: 13 }}>Documentos e status de assinatura</p></div><button onClick={() => setShowForm((value) => !value)} style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--blue)', color: 'white', border: 0, borderRadius: 8, padding: '9px 14px', fontWeight: 700 }}><Plus size={15} /> Novo documento</button></div>{showForm && <form onSubmit={createDocument} style={{ display: 'flex', gap: 10, background: 'var(--bg2)', padding: 16, borderRadius: 10, marginBottom: 16 }}><input required placeholder="Nome do documento" value={form.nome} onChange={(event) => setForm({ ...form, nome: event.target.value })} style={{ flex: 1 }} /><select value={form.tipo} onChange={(event) => setForm({ ...form, tipo: event.target.value })}><option value="contrato">Contrato</option><option value="procuracao">Procuração</option><option value="acordo">Acordo</option><option value="outro">Outro</option></select><button type="submit" style={{ border: 0, borderRadius: 8, background: 'var(--green)', color: 'white', fontWeight: 700, padding: '0 16px' }}>Salvar</button></form>}{documents.length === 0 ? <div style={{ padding: 50, textAlign: 'center', color: 'var(--text3)', background: 'var(--bg2)', borderRadius: 12 }}><FileSignature size={34} /><p>Nenhum documento registrado.</p></div> : <div style={{ display: 'grid', gap: 9 }}>{documents.map((document) => <div key={document.id} style={{ display: 'flex', alignItems: 'center', gap: 13, padding: 15, background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10 }}><FileSignature size={18} color="var(--purple)" /><div style={{ flex: 1 }}><strong>{document.nome}</strong><div style={{ color: 'var(--text3)', fontSize: 12, marginTop: 4 }}>{document.tipo} · {new Date(document.created_at).toLocaleDateString('pt-BR')}</div></div><span style={{ color: document.status === 'assinado' ? 'var(--green)' : 'var(--amber)', fontSize: 12, fontWeight: 700 }}>{statusLabels[document.status] || document.status}</span></div>)}</div>}</div>
}
