import { useEffect, useState } from 'react'
import { Award, Briefcase, Clock, DollarSign } from 'lucide-react'
import { supabase } from '../lib/supabase'

export default function MetricsDashboard() {
  const [metrics, setMetrics] = useState({ success: 0, avgDays: 0, won: 0, lost: 0, revenue: 0, clients: 0 })
  useEffect(() => { (async () => { const [{ data: cases }, { data: honorarios }, { count: clients }] = await Promise.all([supabase.from('casos').select('status,created_at,encerrado_em'), supabase.from('honorarios').select('valor,status'), supabase.from('clientes').select('*', { count: 'exact', head: true })]); const resolved = (cases || []).filter((item) => ['ganho', 'arquivado'].includes(item.status)); const won = (cases || []).filter((item) => item.status === 'ganho').length; const lost = (cases || []).filter((item) => item.status === 'arquivado').length; const days = resolved.map((item) => item.encerrado_em ? (new Date(item.encerrado_em) - new Date(item.created_at)) / 86400000 : null).filter(Boolean); setMetrics({ success: resolved.length ? (won / resolved.length) * 100 : 0, avgDays: days.length ? days.reduce((a, b) => a + b, 0) / days.length : 0, won, lost, revenue: (honorarios || []).filter((item) => item.status === 'recebido').reduce((sum, item) => sum + Number(item.valor || 0), 0), clients: clients || 0 }) })() }, [])
  const cards = [[Award, 'Taxa de êxito', `${metrics.success.toFixed(1)}%`, 'Casos encerrados', 'var(--green)'], [Clock, 'Tempo médio', `${metrics.avgDays.toFixed(0)} dias`, 'Casos com encerramento registrado', 'var(--blue)'], [Briefcase, 'Casos ganhos', metrics.won, `Arquivados: ${metrics.lost}`, 'var(--amber)'], [DollarSign, 'Receita recebida', `R$ ${metrics.revenue.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}`, `${metrics.clients} clientes`, 'var(--purple)']]
  return <div className="fade-in" style={{ padding: 24 }}><h1 style={{ fontSize: 24 }}>Dashboard de Métricas</h1><p style={{ color: 'var(--text3)', fontSize: 13, marginBottom: 20 }}>Indicadores calculados com os dados atuais do escritório</p><div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12 }}>{cards.map(([Icon, label, value, sub, color]) => <div key={label} style={{ background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10, padding: 18 }}><Icon size={18} color={color} /><div style={{ fontSize: 24, fontWeight: 800, marginTop: 12 }}>{value}</div><div style={{ fontWeight: 700, fontSize: 12 }}>{label}</div><div style={{ color: 'var(--text3)', fontSize: 11, marginTop: 3 }}>{sub}</div></div>)}</div></div>
}
