import { useCallback, useEffect, useState } from 'react'
import { Plus, TrendingUp } from 'lucide-react'
import { getCurrentUser, supabase } from '../lib/supabase'

export default function Planejamento() {
  const [plans, setPlans] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [name, setName] = useState('')
  const load = useCallback(async () => { const { data } = await supabase.from('planejamentos').select('*, clientes(nome), casos(titulo)').order('updated_at', { ascending: false }); setPlans(data || []) }, [])
  useEffect(() => { load() }, [load])
  async function createPlan(event) { event.preventDefault(); const user = await getCurrentUser(); if (!user) return alert('Sua sessão expirou. Entre novamente.'); const { data, error } = await supabase.from('planejamentos').insert({ user_id: user.id, nome: name, dados: {} }).select().single(); if (error) return alert(error.message); setPlans((current) => [data, ...current]); setName(''); setShowForm(false) }
  return <div className="fade-in" style={{ padding: 24, maxWidth: 1100 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}><div><h1 style={{ fontSize: 24 }}>Planejamento Previdenciário</h1><p style={{ color: 'var(--text3)', fontSize: 13 }}>Cenários salvos por você, sem dados demonstrativos</p></div><button onClick={() => setShowForm((value) => !value)} style={{ display: 'flex', gap: 6, alignItems: 'center', background: 'var(--blue)', color: 'white', border: 0, borderRadius: 8, padding: '9px 14px', fontWeight: 700 }}><Plus size={15} /> Novo planejamento</button></div>{showForm && <form onSubmit={createPlan} style={{ display: 'flex', gap: 8, marginBottom: 16 }}><input required value={name} onChange={(event) => setName(event.target.value)} placeholder="Nome do planejamento" style={{ flex: 1 }} /><button type="submit" style={{ background: 'var(--green)', color: 'white', border: 0, borderRadius: 8, padding: '0 15px' }}>Criar</button></form>}{plans.length === 0 ? <div style={{ padding: 60, textAlign: 'center', background: 'var(--bg2)', borderRadius: 12, color: 'var(--text3)' }}><TrendingUp size={35} /><p>Nenhum planejamento salvo.</p></div> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(260px,1fr))', gap: 12 }}>{plans.map((plan) => <div key={plan.id} style={{ background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 12, padding: 18 }}><strong>{plan.nome}</strong><p style={{ color: 'var(--text3)', fontSize: 12, marginTop: 8 }}>{plan.clientes?.nome || plan.casos?.titulo || 'Sem cliente ou caso vinculado'}</p><small style={{ color: 'var(--text4)' }}>Atualizado em {new Date(plan.updated_at).toLocaleDateString('pt-BR')}</small></div>)}</div>}</div>
}
