import { useCallback, useEffect, useState } from 'react'
import { BarChart3, Download, FileText } from 'lucide-react'
import { supabase } from '../lib/supabase'

export default function Relatorios() {
  const [rows, setRows] = useState([])
  const [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); const [{ data: cases }, { data: honorarios }] = await Promise.all([supabase.from('casos').select('area,status,created_at'), supabase.from('honorarios').select('valor,status,created_at')]); const map = {}; (cases || []).forEach((item) => { const key = item.area || 'Outros'; map[key] ||= { area: key, casos: 0, ganhos: 0, honorarios: 0 }; map[key].casos += 1; if (item.status === 'ganho') map[key].ganhos += 1 }); (honorarios || []).forEach((item) => { const key = 'Total'; map[key] ||= { area: key, casos: 0, ganhos: 0, honorarios: 0 }; map[key].honorarios += Number(item.valor) || 0 }); setRows(Object.values(map)); setLoading(false) }, [])
  useEffect(() => { load() }, [load])
  function download() { const csv = ['Área,Casos,Ganhos,Honorários', ...rows.map((row) => `${row.area},${row.casos},${row.ganhos},${row.honorarios.toFixed(2)}`)].join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv' })); link.download = 'relatorio-prevos.csv'; link.click(); URL.revokeObjectURL(link.href) }
  return <div className="fade-in" style={{ padding: 24, maxWidth: 1100 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 20 }}><div><h1 style={{ fontSize: 24 }}>Relatórios</h1><p style={{ color: 'var(--text3)', fontSize: 13 }}>Indicadores calculados a partir dos seus dados</p></div><button onClick={download} disabled={!rows.length} style={{ display: 'flex', gap: 6, alignItems: 'center', padding: '9px 14px', border: 0, borderRadius: 8, background: 'var(--blue)', color: 'white', fontWeight: 700 }}><Download size={15} /> Exportar CSV</button></div>{loading ? <div style={{ color: 'var(--text3)' }}>Gerando relatório...</div> : rows.length === 0 ? <div style={{ padding: 50, textAlign: 'center', color: 'var(--text3)', background: 'var(--bg2)', borderRadius: 12 }}><FileText size={34} /><p>Ainda não há dados para gerar relatório.</p></div> : <div style={{ display: 'grid', gap: 14 }}><div style={{ display: 'flex', gap: 10 }}><div style={{ padding: 16, background: 'var(--bg2)', borderRadius: 10, flex: 1 }}><BarChart3 size={18} color="var(--blue)" /><strong style={{ display: 'block', fontSize: 23, marginTop: 8 }}>{rows.reduce((sum, row) => sum + row.casos, 0)}</strong><span style={{ color: 'var(--text3)', fontSize: 12 }}>Casos cadastrados</span></div><div style={{ padding: 16, background: 'var(--bg2)', borderRadius: 10, flex: 1 }}><strong style={{ display: 'block', fontSize: 23 }}>R$ {rows.reduce((sum, row) => sum + row.honorarios, 0).toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</strong><span style={{ color: 'var(--text3)', fontSize: 12 }}>Honorários registrados</span></div></div><table style={{ width: '100%', borderCollapse: 'collapse', background: 'var(--bg2)', borderRadius: 10, overflow: 'hidden' }}><thead><tr>{['Área', 'Casos', 'Ganhos', 'Honorários'].map((header) => <th key={header} style={{ padding: 12, textAlign: 'left', color: 'var(--text3)', fontSize: 12 }}>{header}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.area} style={{ borderTop: '1px solid var(--border)' }}><td style={{ padding: 12 }}>{row.area}</td><td style={{ padding: 12 }}>{row.casos}</td><td style={{ padding: 12 }}>{row.ganhos}</td><td style={{ padding: 12 }}>R$ {row.honorarios.toLocaleString('pt-BR', { minimumFractionDigits: 2 })}</td></tr>)}</tbody></table></div>}</div>
}
