import { useCallback, useEffect, useState } from 'react'
import { CalendarPlus, Link as LinkIcon, Video } from 'lucide-react'
import { getCurrentUser, supabase } from '../lib/supabase'

export default function Reunioes() {
  const [meetings, setMeetings] = useState([])
  const [showForm, setShowForm] = useState(false)
  const [form, setForm] = useState({ titulo: '', data_inicio: '', duracao_minutos: 30, link: '' })
  const load = useCallback(async () => { const { data } = await supabase.from('reunioes').select('*, clientes(nome)').order('data_inicio'); setMeetings(data || []) }, [])
  useEffect(() => { load() }, [load])
  async function createMeeting(event) { event.preventDefault(); const user = await getCurrentUser(); if (!user) return alert('Sua sessão expirou. Entre novamente.'); const { data, error } = await supabase.from('reunioes').insert({ ...form, user_id: user.id, data_inicio: new Date(form.data_inicio).toISOString(), duracao_minutos: Number(form.duracao_minutos) }).select('*, clientes(nome)').single(); if (error) return alert(error.message); setMeetings((current) => [...current, data]); setForm({ titulo: '', data_inicio: '', duracao_minutos: 30, link: '' }); setShowForm(false) }
  return <div className="fade-in" style={{ padding: 24, maxWidth: 1000 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 18 }}><div><h1 style={{ fontSize: 24 }}>Reuniões</h1><p style={{ color: 'var(--text3)', fontSize: 13 }}>Reuniões reais vinculadas ao escritório</p></div><button onClick={() => setShowForm((value) => !value)} style={{ display: 'flex', gap: 6, alignItems: 'center', padding: '9px 14px', border: 0, borderRadius: 8, background: 'var(--blue)', color: 'white', fontWeight: 700 }}><CalendarPlus size={15} /> Nova reunião</button></div>{showForm && <form onSubmit={createMeeting} style={{ display: 'grid', gridTemplateColumns: '2fr 1fr 1fr', gap: 10, background: 'var(--bg2)', padding: 16, borderRadius: 10, marginBottom: 16 }}><input required placeholder="Título" value={form.titulo} onChange={(event) => setForm({ ...form, titulo: event.target.value })} /><input required type="datetime-local" value={form.data_inicio} onChange={(event) => setForm({ ...form, data_inicio: event.target.value })} /><input type="number" min="15" step="15" value={form.duracao_minutos} onChange={(event) => setForm({ ...form, duracao_minutos: event.target.value })} /><input placeholder="Link da reunião" value={form.link} onChange={(event) => setForm({ ...form, link: event.target.value })} /><button type="submit" style={{ border: 0, borderRadius: 8, background: 'var(--green)', color: 'white', fontWeight: 700 }}>Salvar</button></form>}{meetings.length === 0 ? <div style={{ padding: 50, textAlign: 'center', color: 'var(--text3)', background: 'var(--bg2)', borderRadius: 12 }}>Nenhuma reunião cadastrada.</div> : <div style={{ display: 'grid', gap: 9 }}>{meetings.map((meeting) => <div key={meeting.id} style={{ display: 'flex', alignItems: 'center', gap: 14, padding: 15, background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10 }}><Video size={18} color="var(--blue)" /><div style={{ flex: 1 }}><strong>{meeting.titulo}</strong><div style={{ fontSize: 12, color: 'var(--text3)', marginTop: 4 }}>{new Date(meeting.data_inicio).toLocaleString('pt-BR')} · {meeting.duracao_minutos} min · {meeting.clientes?.nome || 'Sem cliente vinculado'}</div></div>{meeting.link && <a href={meeting.link} target="_blank" rel="noreferrer" style={{ color: 'var(--blue)' }}><LinkIcon size={15} /></a>}</div>)}</div>}</div>
}
