import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Methods":"POST, OPTIONS","Access-Control-Allow-Headers":"authorization, x-client-info, content-type"};

interface PaymentRequest {lead_email:string;lead_nome:string;amount_cents:number;description?:string;lead_id?:string;user_id:string;}

async function createAsaasPayment(req:PaymentRequest):Promise<Response>{try{const apiKey=Deno.env.get("ASAAS_API_KEY");if(!apiKey){return new Response(JSON.stringify({success:false,error:"ASAAS not configured"}),{status:500,headers:{"Content-Type":"application/json",...corsHeaders}});}const dueDate=new Date();dueDate.setDate(dueDate.getDate()+3);const payload={customer:{name:req.lead_nome,email:req.lead_email},value:req.amount_cents/100,dueDate:dueDate.toISOString().split('T')[0],description:req.description||"Pagamento",notificationUrl:`${Deno.env.get("APP_URL")}/webhooks/asaas`,externalReference:req.lead_id||""};const response=await fetch("https://api.asaas.com/v3/payments",{method:"POST",headers:{"Authorization":`Bearer ${apiKey}`,"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json()as any;if(!response.ok){return new Response(JSON.stringify({success:false,error:data.errors?.[0]?.description||"ASAAS error"}),{status:400,headers:{"Content-Type":"application/json",...corsHeaders}});}const supabase=createClient(Deno.env.get("SUPABASE_URL")||"",Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"");await supabase.from("pagamentos").insert({user_id:req.user_id,lead_id:req.lead_id,gateway:"asaas",valor_cents:req.amount_cents,moeda:"brl",status:"pendente",session_id:data.id,descricao:req.description});return new Response(JSON.stringify({success:true,checkout_url:data.invoiceUrl,session_id:data.id}),{status:200,headers:{"Content-Type":"application/json",...corsHeaders}});}catch(error){console.error("Error:",error);return new Response(JSON.stringify({success:false,error:"Internal error"}),{status:500,headers:{"Content-Type":"application/json",...corsHeaders}});}}

async function handleRequest(request:Request):Promise<Response>{if(request.method==="OPTIONS")return new Response("ok",{headers:corsHeaders});if(request.method!=="POST")return new Response("Method not allowed",{status:405,headers:corsHeaders});try{const authHeader=request.headers.get("authorization");if(!authHeader?.startsWith("Bearer ")){return new Response(JSON.stringify({success:false,error:"Missing auth"}),{status:401,headers:{"Content-Type":"application/json",...corsHeaders}});}const body=await request.json()as PaymentRequest;if(!body.lead_email||!body.lead_nome||!body.amount_cents||!body.user_id){return new Response(JSON.stringify({success:false,error:"Missing required fields"}),{status:400,headers:{"Content-Type":"application/json",...corsHeaders}});}return await createAsaasPayment(body);}catch(error){console.error("Error:",error);return new Response(JSON.stringify({success:false,error:"Invalid request"}),{status:400,headers:{"Content-Type":"application/json",...corsHeaders}});}}

Deno.serve(handleRequest);